### ISSUE TITLE
python eroor when excecuting

### ISSUE THREAD

**Issue by Noam1985** [pierluigiderosa/Qgis2Ras#8]
i tried to excecute the plugin and i always get an error involoved with python. I already changed no data values in my raster to 0.

I would appriciate any help.

this is the error message:

An error has occurred while executing Python code: 

TypeError: 'NoneType' object is not iterable 
Traceback (most recent call last):
  File "C:/Users/User/.qgis2/python/plugins\Qgis2Ras\qras_dialog.py", line 113, in runProfile
    main(self.river,self.XSection,self.textfile,self.dem,resolution)
  File "C:/Users/User/.qgis2/python/plugins\Qgis2Ras\RASout.py", line 286, in main
    output_centerline(river,xsections, outfile,rlayer)
  File "C:/Users/User/.qgis2/python/plugins\Qgis2Ras\RASout.py", line 130, in output_centerline
    (X,Y,Z) = queryRaster(point,rlayer)
TypeError: 'NoneType' object is not iterable

**Comment by pierluigiderosa** [comment]
This means that raster data and vector data does not overlaps. Maybe vector layer is outside the raster data.
